# Generated by Django 2.1.4 on 2019-01-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_time', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_time', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_time', models.DateTimeField(verbose_name='date')),
                ('user_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.Manager')),
            ],
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.User'),
        ),
    ]
